# Generated by Django 6.0.3 on 2026-03-22 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_otpverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trusteddevice',
            name='device_fingerprint',
            field=models.CharField(max_length=64),
        ),
    ]
