# Generated by Django 6.0.3 on 2026-03-18 15:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('transaction_type', models.CharField(choices=[('send', 'Send Money'), ('receive', 'Receive Money'), ('deposit', 'Deposit'), ('withdrawal', 'Withdrawal')], default='send', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('blocked', 'Blocked')], default='pending', max_length=20)),
                ('sender_balance_before', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sender_balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('receiver_balance_before', models.DecimalField(decimal_places=2, max_digits=12)),
                ('receiver_balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('risk_score', models.FloatField(default=0)),
                ('risk_level', models.IntegerField(choices=[(0, 'Low'), (1, 'Medium'), (2, 'High')], default=0)),
                ('mfa_required', models.BooleanField(default=False)),
                ('mfa_completed', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_fingerprint', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_transactions', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='transaction_created_fc4c1b_idx'), models.Index(fields=['sender', '-created_at'], name='transaction_sender__a10924_idx'), models.Index(fields=['receiver', '-created_at'], name='transaction_receive_5a53aa_idx')],
            },
        ),
    ]
